-- Reset receipt number sequences to start from 1 again
-- Run this AFTER clearing all receipt data

-- Step 1: Check current max receipt numbers (should be 0 or NULL after deletion)
SELECT 
  'deal_receipts' as table_name,
  MAX(CAST(SUBSTRING(receipt_number FROM '[0-9]+') AS INTEGER)) as max_number
FROM deal_receipts
UNION ALL
SELECT 
  'virtual_receipts' as table_name,
  MAX(CAST(SUBSTRING(receipt_number FROM '[0-9]+') AS INTEGER)) as max_number
FROM virtual_receipts;

-- Step 2: Check if there are sequences for receipt numbering
SELECT 
  schemaname,
  sequencename,
  last_value,
  start_value,
  increment_by
FROM pg_sequences
WHERE sequencename LIKE '%receipt%';

-- Step 3: If receipt_number is generated by application logic (not a sequence),
-- the next receipt will start from the pattern defined in code.
-- Check the current state of all receipts to see the numbering pattern:
(SELECT 
  'deal_receipts' as source,
  receipt_number,
  created_at
FROM deal_receipts
ORDER BY created_at DESC
LIMIT 10)
UNION ALL
(SELECT 
  'virtual_receipts' as source,
  receipt_number,
  created_at
FROM virtual_receipts
ORDER BY created_at DESC
LIMIT 10)
ORDER BY created_at DESC;

-- Step 4: Find the next receipt number that will be generated
-- (This depends on how receipt numbers are generated in the app)
-- Common patterns:
-- - TP-MOM-00001 (Trusted Partner - Business - Number)
-- - VR-00001 (Virtual Receipt - Number)

-- To ensure receipts start from 1 after cleanup:
-- The application code likely queries MAX(receipt_number) and increments
-- Since all receipts are deleted, the next receipt should start from 00001

-- Verification: Check if any receipts still exist
SELECT COUNT(*) as total_receipts FROM deal_receipts
UNION ALL
SELECT COUNT(*) as total_virtual_receipts FROM virtual_receipts;
